export { default as AuthTabs } from './AuthTabs/AuthTabs'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
